### PR TITLE
Adds comments for what to remove if not using CDQ

### PR DESCRIPTION
**Pull request by markrickert**

### CODE REVIEW

**Comment by squidpunch** [comment]
@markrickert I think we have this covered with the CLI client - maybe we need to clarify that a bit more in the readme, docs or something?

```
   You can remove CDQ or afmotion if your project does not use it
     > potion remove cdq
     > potion remove afmotion
```

**Comment by markrickert** [comment]
I just breezed over that in the cli when i created the project. perhaps this isn't needed then. I just removed the gems manually and then wound up with some rake issues because of the task not being removed and then issues with the app delegate. Maybe this is just superfluous for people who don't read directions?

**Comment by squidpunch** [comment]
yeah the way we do the removals i believe **should** still work with the comments added. 

So like you said, those that don't use the cli, or those that dont read directions may get into the state you are talking about probably get errors like you ddi too and the comments would make ti clear that its cool to remove them if you are removing the gem.

**Comment by jamonholmgren** [comment]
I've run into the same thing as Mark, probably because I too don't read CLI instructions as carefully as I should.

**Comment by squidpunch** [comment]
Merging is fine with me, we should check that we have this documented, but like I said. I don't see harm in adding comments if your down the path both of you journeyed.

**Pull request merged**
