### PR TITLE
SDK 8.3 now that xcode 6.3 is released

### PR DESCRIPTION
**Pull request by squidpunch**
I wonder if we should just have them all as comments, which defaults to whatever you have installed, or if we should still expect you run the latest (and need to bump this each release of xcode....)

### CODE REVIEW

**Comment by GantMan** [comment]
Why do we specify the SDK?  doesn't it grab the latest by default?   Specifying the SDK feels like unnecessary clutter.

**Comment by squidpunch** [comment]
yeah somewhat what I was asking as well.  but it was already in there - so when I built a new app i got an error because I have 8.2, not 8.1

that being said.  On my team we do specify it, mostly just to make sure we are all running the same beast - so I am not compiling with 8.2, and others are compiling with 8.2 - but this is a change that a application team can decide and add to the rakefile themselves instead of us putting it in by default.

I can also PR removing it *shrug* - thats why i posed the question in the description.

**Comment by GantMan** [comment]
imo -    Leave it there commented out.   With a friendly explanation on why anyone would specify.   "If you would like to specify the SDK to assure consistency across multiple machines, uncomment this"

We'll still need to update the number in the commented out file, but we'll be less annoying to most people :)

**Comment by dmarkow** [comment]
:+1:

Just ran into this with Xcode 6.3. `potion create my_app` manually specified 8.2 which I had to change/remove before I could run the app. I agree that letting RubyMotion's default handling take over, with the commented option to reference a specific SDK version.

**Comment by squidpunch** [comment]
oh, i thought this got merged, looks like it needs a rebase, I will do that now :+1:

**Pull request merged**
